version: "3.1"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/usr/share/nginx/html
    networks:
      - mysql_network # Connect Nginx to the custom network

  php-fpm:
    build: .
    container_name: php-fpm-container
    volumes:
      - ./php:/usr/share/nginx/html
    networks:
      - mysql_network # Connect PHP-FPM to the custom network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Nik@1631 # Set the root password
      MYSQL_DATABASE: "Lab3"
    volumes:
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - mysql_network # Connect MySQL to the custom network

networks:
  mysql_network:
    driver: bridge # Use the bridge network driver
