version: "3.1"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/usr/share/nginx/html
    networks:
      - app_network

  php-fpm:
    build: .
    container_name: php-fpm-container
    volumes:
      - ./php:/usr/share/nginx/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge